password:
  weakness: Пароль слишком слабый
  sameness: Пароли не совпадают
username:
  not_found: Пользователь не найден
  shortness: Логин слишком короткий
  exists: Такой логин уже существует
  lang: Логин не должен содержать русские символы
email:
  validity: Почта не прошла проверку
  exists: Пользователь с таким email уже зарегистрирован
birthday:
  too_much: Этому старику здесь делать нечего
  wrong_format: Неправильный формат даты
movie:
  exists: Данный фильм уже добавлен
tv:
  exists: Данный сериал уже добавлен
episode:
  exists: Данный эпизод уже добавлен
  upcoming: Данные эпизод ещё не вышел
seasons:
  invalid_meta: Метаданные сезонов не соотвествуют количеству сезонов
common:
  field_absence: Обязательные поля отсутствуют
  bad_params: Ошибка валидации полей
  not_found: Указанный файл не найден
  exact_not_found: Файл <filename> не найден
  connection_error: Ошибка подключения. Проверьте интернет соединение
  response_error: Ошибка ответа от сервера. Ответ в неправильном формате
  slow_internet_connection: Подключение было разорвано в связи с долгим подключение к серверу
  cross_app_failed: Ошибка подключения к СКП
queue:
  type_error: Указан неправильный формат строки
download:
  unknown: Неизвестная ошибка при скачивании
voice:
  not_found: Указана неправильная озвучка